# ===============================
# Inference Configuration (RCOD)
# ===============================

model:
  weights_dir: ../../models/pytorch
  device: cuda
  half: false        # FP16 inference 여부

data:
  test_dir: ../../data/rcod/images/val_fold1
  gt_json: ../../data/rcod/json/val_fold1.json
  img_width: 1920
  img_height: 1200

inference:
  imgsz: 640
  conf_thres: 0.25
  iou_thres: 0.5
  stream: true

evaluation:
  iou_threshold: 0.5
  ap_log: ap_info.txt

output:
  output_dir: ./outputs